/**
 * Represents a single comment generated by the AI on a specific line of a file.
 */
export interface ReviewComment {
  /** The relative path to the file in the repository. */
  file: string;
  /** The specific line number where the comment should be applied. */
  line: number;
  /** The feedback provided by the AI. */
  comment: string;
}

/**
 * The structured response format expected from the Gemini AI model.
 */
export interface ReviewResponse {
  /** An array of line-level review comments. */
  reviews: ReviewComment[];
}

/**
 * The data structure passed to the BullMQ review processing job.
 */
export interface JobPayload {
  /** The internal database ID of the repository. */
  repoId: number;
  /** The GitHub pull request number. */
  prNumber: number;
  /** The GitHub App installation ID for authentication. */
  installationId: number;
  /** The SHA of the head commit to ensure we review the correct version. */
  commitSha: string;
}

/**
 * Minimal interface for the GitHub Webhook payload for Pull Request events.
 * Used to filter and route events to the processing queue.
 */
export interface GithubWebhookPayload {
  /** The action performed (e.g., 'opened', 'synchronize'). */
  action: string;
  /** Repository details. */
  repository: {
    /** The unique GitHub ID for the repository. */
    id: number;
    /** The full name including owner (e.g., 'owner/repo'). */
    full_name: string;
  };
  /** Pull request details. */
  pull_request: {
    /** The PR number. */
    number: number;
    /** Information about the head of the PR. */
    head: {
      /** The commit SHA at the head of the branch. */
      sha: string;
    };
  };
  /** App installation details. */
  installation: {
    /** The ID assigned when the app was installed on the account/org. */
    id: number;
  };
}
