import { PricingFeature } from "@/types/Pricing";

export const PRICING_FEATURES: PricingFeature[] = [
  {
    name: "Unlimited Public PRs",
    solo: true,
    pro: true,
    enterprise: true,
    detail: "Standard architectural check on all open source work.",
  },
  {
    name: "Private Repositories",
    solo: false,
    pro: true,
    enterprise: true,
    detail: "Secure scanning for internal team codebases.",
  },
  {
    name: "Standard AI Scan",
    solo: true,
    pro: true,
    enterprise: true,
    detail: "Basic syntax, linting, and obvious logic flaw detection.",
  },
  {
    name: "Architectural Analysis",
    solo: false,
    pro: true,
    enterprise: true,
    detail: "Deep dependency mapping and pattern recognition.",
  },
  {
    name: "Security Audit (Advanced)",
    solo: false,
    pro: "Partial",
    enterprise: true,
    detail: "Taint analysis for SQLi, XSS, and broken access control.",
  },
  {
    name: "Slack/Discord Integration",
    solo: false,
    pro: true,
    enterprise: true,
    detail: "Real-time alerts directly in your team's chat.",
  },
  {
    name: "Priority Scan Queue",
    solo: false,
    pro: true,
    enterprise: true,
    detail: "Average wait time < 30s during peak traffic.",
  },
  {
    name: "Single Sign-On (SSO)",
    solo: false,
    pro: false,
    enterprise: true,
    detail: "Okta, Azure AD, and Custom SAML support.",
  },
  {
    name: "Self-Hosted Agent",
    solo: false,
    pro: false,
    enterprise: true,
    detail: "Run Git Merge Buddy within your own VPC or cluster.",
  },
  {
    name: "Custom Guardrails",
    solo: false,
    pro: false,
    enterprise: true,
    detail: "Define team-specific linting and logic policies.",
  },
  {
    name: "SLA Guarantee",
    solo: false,
    pro: false,
    enterprise: true,
    detail: "99.9% uptime commitment for Enterprise partners.",
  },
  {
    name: "Dedicated Support",
    solo: false,
    pro: "Email",
    enterprise: "24/7 Phone",
    detail: "Direct line to our senior engineering team.",
  },
];
